# Configuration file for Talia

talia:
  author: Nightwolf
  version: 1.0.0
  check_for_update: false

database:
  host: 127.0.0.1
  username: root
  password: root
  name: talia

realm:
  host: 127.0.0.1
  port: 444

world:
  host: 127.0.0.1
  port: 5556

security:
  client_version: 1.29.1
  allow_multi_account: true
